[core]
fastForwardRatio=4           ; Limite l'accélération à 400% (Mettre à 0 pour illimité)


# Paramètres généraux d'affichage (Exemple pour mgba-sdl)
[ports.sdl]
fullscreen=0
lockAspectRatio=1
lockIntegerScaling=1

[shortcuts.QT_K]
emulation.fastForward=Tab

# CONFIGURATION DU CLAVIER (Interface Qt / mgba-qt)
# Utilise les Keycodes de Qt (ex: Z=90, X=88, Entrée=16777220)
[input.QT_K]
keyA=H   ; Touche pour le bouton A (Ex: Retour arrière / Backspace)
keyB=K         ; Touche pour le bouton B (Ex: Z)
keyL=U         ; Touche pour L (Ex: A)
keyR=I         ; Touche pour R (Ex: S)
keyStart=16777220 ; Touche Start (Ex: Entrée)
keySelect=88    ; Touche Select (Ex: X)
keyUp=Z    ; Flèche Haut
keyDown=S  ; Flèche Bas
keyLeft=Q  ; Flèche Gauche
keyRight=D ; Flèche Droite



# CONFIGURATION DU CLAVIER (Version Terminal / mgba-sdl)
# Utilise les codes décimaux standard de la bibliothèque SDL2
[gba.input.SDLK]
# keyA=107        ; Touche K
# keyB=106        ; Touche J
# keyL=113        ; Touche Q
# keyR=111        ; Touche O
# keyStart=13     ; Touche Entrée (Code SDL 13)
# keySelect=8     ; Touche Retour arrière (Code SDL 8)
# keyUp=119       ; Touche W (Haut)
# keyDown=115     ; Touche S (Bas)
# keyLeft=97      ; Touche A (Gauche)
# keyRight=100    ; Touche D (Droite)
keyA=104        ; Touche H
keyB=107        ; Touche K
keyL=117        ; Touche U
keyR=105        ; Touche I
keyStart=13     ; Touche Entrée
keySelect=8     ; Touche Retour arrière (Backspace)
keyUp=122       ; Touche Z (Haut)
keyDown=115     ; Touche S (Bas)
keyLeft=113     ; Touche Q (Gauche )
keyRight=100    ; Touche D (Droite)

# CONFIGURATION D'UNE MANETTE USB/BLUETOOTH (Via SDL)
# Les chiffres correspondent aux index des boutons physiques de votre manette
[gba.input.SDLB]
buttonA=0       ; Bouton 0 (souvent Cross/A)
buttonB=1       ; Bouton 1 (souvent Circle/B)
buttonL=4       ; Gâchette gauche (L1)
buttonR=5       ; Gâchette droite (R1)
buttonStart=7   ; Bouton Options / Start
buttonSelect=6  ; Bouton Share / Select
